export const GET_ALL_PRODUCTS = '/products';
export const GET_PRODUCT = (id: string = '') => `/products/find/${id}`;
export const CREATE_PRODUCT = '/products';
export const UPDATE_PRODUCT = (id: string = '') => `/products/${id}`;
export const DELETE_PRODUCT = (id: string = '') => `/products/${id}`;
export const GET_ALL_PAYMENTS = '/payments';
export const PROCESS_PAYMENT = '/payments/checkout';
export const LOGIN = '/auth/login';
export const REGISTER = '/auth/register';
export const GET_CART = (id: string = '') => `/carts/find/${id}`;
export const SAVE_CART = `/carts`;
export const UPDATE_CART = (id: string = '') => `/carts/${id}`;
export const DELETE_CART = (id: string = '') => `/carts/${id}`;
export const GET_ORDERS = (id: string = '') => `/orders/find/${id}`;
export const GET_ALL_ORDERS = '/orders';
export const CREATE_ORDER = '/orders';
export const UPDATE_ORDER = (id: string = '') => `/orders/${id}`;
export const DELETE_ORDER = (id: string = '') => `/orders/${id}`;
export const GET_ALL_USERS = '/users';
export const GET_USER = (id: string) => `/users/find/${id}`;
export const UPDATE_USER = (id: string) => `/users/${id}`;
export const DELETE_USER = (id: string) => `/users/${id}`;
export const GET_USER_STATISTIC = '/users/stats';
export const GET_ORDER_STATISTIC = '/orders/stats';